# Generated by Django 4.0 on 2021-12-24 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'brand',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('birthdate', models.DateField()),
                ('phone_number', models.IntegerField(blank=True, null=True)),
                ('address', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'client',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('new', models.BooleanField(default=True)),
                ('doors', models.IntegerField(default=3)),
                ('cubic_capacity', models.IntegerField()),
                ('power', models.IntegerField()),
                ('brand', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='car_dealership.brand')),
                ('id_client', models.ForeignKey(blank=True, db_column='id_client', default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='car_dealership.client')),
            ],
            options={
                'db_table': 'car',
                'managed': True,
            },
        ),
    ]
